### ISSUE TITLE
VS 2022, Unrecognized command or argument '--type-access-modifier'  'public.

### ISSUE THREAD

**Issue by HarminderArtesianIo** [christianhelle/apiclientcodegen#1016]
**Type Access modifier for Generated Types "Public" is not working**
I was able to generate the Api client earlier without any issues with VS2022 and extension REST API Client Code Generator .
But now after upgrading the Rest API Client Tool in Vs2022.

**Support Key**: `29fd6a4` *Found in **Tools -> Options -> REST API Client Code Generator - Analytics***

**To Reproduce**
1. Right click C# project in Vs2022
2. Add > New Rest Api client > Generate with Microsoft Kiota (v.1.19.0)
3. Paste path of my Swagger file http://localhost:5000/swagger/v1/swagger.json
4. Click OK
5. Swagger file is added to my project
6. But the swagger.cs file is not getting generated. It is giving me error. 

Error:
Unrecognized command or argument '--type-access-modifier'.
Unrecognized command or argument 'Public'.

When i changed Type access modifier to protected. Error changed to 

Unrecognized command or argument '--type-access-modifier'.
Unrecognized command or argument 'protected'.

Vs 2022, screenshot for your reference is attached here:
<img width="377" alt="image" src="https://github.com/user-attachments/assets/d9a543d0-483f-4377-bcda-2947ba57fea1">

**Comment by HarminderArtesianIo** [comment]
@christianhelle   This is resolved. 
Thank you for your prompt reply and resolution.

 I was busy with a personal thing at home , I apologize for late reply.

**Comment by christianhelle** [comment]
I would be very grateful for a rating or review on the [Visual Studio Marketplace](https://bit.ly/rapicgen-vs2022)
