### ISSUE TITLE
[OpenAPI Generator] Add option to generate code with EmitDefaultValue=false

### ISSUE THREAD

**Issue by christianhelle** [christianhelle/apiclientcodegen#246]
This is based on a comment in the Marketplace Q&A section by Bin Sun

> Hi Chris, 
> 
> Thanks for the great tools however I found when the open api generator generates the C# code based on yaml file it will set EmitDefaultValue to false as default. 
> 
> According to Microsoft's document https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-member-default-values this value is default to true and needs a very specific need to set as false.  
> 
> This is fatal coz it will eliminate the field in request if there is default value passed to the field. E.g. when I set an integer field value to 0 then this integer field disappears from my request.  
> 
> After some digging I found it is an known issue fixed in open api generator 4.2.0 https://github.com/OpenAPITools/openapi-generator/pull/4010. Is it ok to add  --additional-properties optionalEmitDefaultValues=true to the open api generator command?  
> 
> Cheers

**Comment by bllue78** [comment]
Thanks Chris! Actually, it needs to be EmitDefaultValue=true as my comment.

**Comment by christianhelle** [comment]
@bllue78 I implemented the change and started a build. I'll attach the built VSIX to this issue once its done and would like to ask you to do a quick test if it does the trick for you

I generated code using the Swagger Petstore v3 spec and properties of the contracts are generated like this

``` 
/// <summary>
/// Gets or Sets Id
/// </summary>
[DataMember(Name = "id", EmitDefaultValue = true)]
public long Id { get; set; }
```

**Comment by christianhelle** [comment]
@bllue78 

The OpenAPI Generator CLI is launched using the following arguments

```
generate --generator-name csharp-netcore --input-spec "Swagger.yaml" --output ".\89ac5a4031bb431ebdeae65c4ba39386\TempApiClient" --package-name "GeneratedCode" --global-property apiTests=false,modelTests=false --skip-overwrite --additional-properties optionalEmitDefaultValues=true
```

The arguments above are copy/pasted from my automated smoke test script so please ignore the random looking GUID's and paths

**Comment by christianhelle** [comment]
@bllue78 Here's a development build that contains the change

[ApiClientCodeGenerator-1.2.7565.zip](https://github.com/christianhelle/apiclientcodegen/files/6961408/ApiClientCodeGenerator-1.2.7565.zip)

**Comment by bllue78** [comment]
Hi Chris, sorry to reply late. I've tried the development build and the "generate with Open API" command works perfectly! Thanks for the fix. 
One thing I want to mention is when I right-click the YAML file and try to regenerate the code the existing code doesn't get updated.
When I tried to make a small change in the YAML file and then the existing code getting updated as I expected.
Thanks for your help!

**Comment by christianhelle** [comment]
Awesome! I'm working on a settings page for this incase someone wants to explicitly disable it
> Hi Chris, sorry to reply late. I've tried the development build and the "generate with Open API" command works perfectly! Thanks for the fix.

Thanks for mentioning this. This is unfortunately a known issue that I have yet to figure out a proper solution for. What the "Generate with OpenAPI" context menu does is actually just set the custom tool of the project item. Changing the custom tool value will automatically run the custom tool. I was able to cheat this before by removing the custom tool and setting it again but that wasn't really a very elegant solution. I do know the project item upon right click and I do know of a fix so I will, hopefully, eventually fix this
> One thing I want to mention is when I right-click the YAML file and try to regenerate the code the existing code doesn't get updated.
> When I tried to make a small change in the YAML file and then the existing code getting updated as I expected.

You're welcome
> Thanks for your help!

**Comment by christianhelle** [comment]
I merged in the changes and will be releasing a new build today

**Comment by christianhelle** [comment]
This is resolved in [this build](https://github.com/christianhelle/apiclientcodegen/releases/tag/1.3.7613) and is available from the Visual Studio Marketplace
