### ISSUE TITLE
Add support for portable java

### ISSUE THREAD

**Issue by Jogai** [christianhelle/apiclientcodegen#28]
I always use the zipped binaries from https://adoptopenjdk.net for running java programs. And dont add it to my path. For me it would be nice to be able to configure the java path.

**Comment by christianhelle** [comment]
Oh cool, I never even heard of the OpenJDK. I'll give this some thought. I'm starting to think out a User Settings screen and option pages. This is exactly one of the things that can go in there. I would probably by default still use the JDK provided by Oracle but I will try my best to allow a smoother switch. 

Currently I just guess/assume the locations of the tools I piggy back on, and of course this is not really a long term feasible solution

Thanks for suggesting this :)

**Comment by Jogai** [comment]
Assume default paths unless configured seems a good strategy.

Important note on why I use a different build for java: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

**Comment by christianhelle** [comment]
Oh wow! I didn't notice this at all! Thanks for the heads up on this... 

This is will have a huge impact on Android developers

```
Important Oracle JDK License Update

The Oracle JDK License has changed for releases starting April 16, 2019.

The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses. The new license permits certain uses, such as personal use and development use, at no cost -- but other uses authorized under prior Oracle JDK licenses may no longer be available. Please review the terms carefully before downloading and using this product. An FAQ is available here. 

Commercial license and support is available with a low cost Java SE Subscription. 

Oracle also provides the latest OpenJDK release under the open source GPL License at jdk.java.net.
```

**Comment by christianhelle** [comment]
So I had a little time to dig in a bit more into this today. Apparently I forgot how I wrote my code! Doh! So I'm actually not assuming anything regarding Java, I do that only for AutoRest with Node and NPM but not with Java. I just blindly trust that Java is installed and start the process java with the arguments for Swagger Codegen CLI or OpenAPI Generator. To verify that the OpenJDK works I uninstalled all traces of the Oracle JDK and installed the [OpenJDK 8 from AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b04/OpenJDK8U-jdk_x64_windows_hotspot_8u212b04.msi) and the Swagger Codegen CLI and OpenAPI Generator code generators just work

One thing to note was that when I installed the OpenJDK I enabled setting the JAVA_HOME environment variables and the default Oracle JDK registry entries. These are disabled by default when installing OpenJDK from the MSI package. I haven't tried the zip distribution yet but I will try that out when I get the time again

I started work on the option pages and will add a feature that allows you to specify a custom path to **Java**, **NSwag**, and **NPM**. I'm some what re-creating the available options in NSwag Studio but I'm starting with the ones that I actually use and change, after all I use this tool several times a day :)

**Comment by christianhelle** [comment]
I found time today to finish this up. The options page will looks like this:

![General Options Page](https://raw.githubusercontent.com/christianhelle/apiclientcodegen/44a904b8e40a5a2ae3aee26bb338a7ba45b1355f/images/options-general.png)

@Jogai I built this for you so if you want anything changed then please feel free to suggest
