### ISSUE TITLE
Possibility to choose OpenAPI client generator and configure generator specific additional-properties

### ISSUE THREAD

**Issue by ruudsieb** [christianhelle/apiclientcodegen#361]
There is only 1 option for the OpenAPI generator (Emit default value).
I would like to have an option to choose the client generator for OpenAPI (see list here: https://openapi-generator.tech/docs/generators), or at least choose between the csharp generators, and configure the generator specific options as additional-properties.

To prevent too much maintenance, it would be okay for me if it would be possible to edit the raw commandline which is used, instead of changing the parameters in the property grid.

**Comment by christianhelle** [comment]
Thanks for suggesting this. I will start implementing this after the easter holidays
