### ISSUE TITLE
Missing way to set ParameterDateTimeFormat for NSwag

### ISSUE THREAD

**Issue by johnwc** [christianhelle/apiclientcodegen#420]
When using the `NSwagCodeGenerator`, there is little options in tools->options. Need to be able to set other options than what is given, specifically at this time the `ParameterDateTimeFormat` option.

Other options available: https://github.com/RicoSuter/NSwag/wiki/CSharpClientGeneratorSettings

Can these settings be placed in the project file, to be applied per project instead of globally?

**Comment by christianhelle** [comment]
Thanks again for reporting this @johnwc 

I will add the `ParameterDateTimeFormat` option to the Visual Studio options page for NSwag

To avoid repeating myself regarding a per-project configuration I will link to [my comment](https://github.com/christianhelle/apiclientcodegen/issues/421#issuecomment-1279910905) in Issue #421

**Comment by christianhelle** [comment]
I will try to add as many settings as I can from the link you provided

**Comment by christianhelle** [comment]
I started working on a file format that can describe which code generator to use and with what settings. This will eventually get a context menu for itself within Visual Studio where a user will be able to click "Generate Code..." or something like that
