### ISSUE TITLE
Support for Refit

### ISSUE THREAD

**Issue by Nonobis** [christianhelle/apiclientcodegen#467]
**Is your feature request related to a problem? Please describe.**
I don't kown if this possible with you tool, but could you generate code compatible with the Refit Library ?

**Describe the solution you'd like**
Generate a Client using the Refit libraty for dotnet ?

https://github.com/reactiveui/refit

**Comment by christianhelle** [comment]
First of all, thank you for taking your time to suggest this

This is unfortunately no trivial task to do but I will keep this issue open in case I find a decent way to implement it

**Comment by christianhelle** [comment]
Just so you know @Nonobis, I have started working on this.

As of now, I can generate the following interface based on the Swagger Petstore example OpenAPI spec

```cs
using Refit;

public interface IApiClient
{
	[Put("/pet")]
	Task<object> UpdatePet();

	[Post("/pet")]
	Task<object> AddPet();

	[Get("/pet/findByStatus")]
	Task<object> FindPetsByStatus();

	[Get("/pet/findByTags")]
	Task<object> FindPetsByTags();

	[Get("/pet/{petId}")]
	Task<object> GetPetById(string petId);

	[Post("/pet/{petId}")]
	Task UpdatePetWithForm(string petId);

	[Delete("/pet/{petId}")]
	Task DeletePet(string petId);

	[Post("/pet/{petId}/uploadImage")]
	Task<object> UploadFile(string petId);

	[Get("/store/inventory")]
	Task<object> GetInventory();

	[Post("/store/order")]
	Task<object> PlaceOrder();

	[Get("/store/order/{orderId}")]
	Task<object> GetOrderById(string orderId);

	[Delete("/store/order/{orderId}")]
	Task DeleteOrder(string orderId);

	[Post("/user")]
	Task CreateUser();

	[Post("/user/createWithList")]
	Task<object> CreateUsersWithListInput();

	[Get("/user/login")]
	Task<object> LoginUser();

	[Get("/user/logout")]
	Task LogoutUser();

	[Get("/user/{username}")]
	Task<object> GetUserByName(string username);

	[Put("/user/{username}")]
	Task UpdateUser(string username);

	[Delete("/user/{username}")]
	Task DeleteUser(string username);
}
```

I'm still working on the details regarding return types and parameters but I'm on a roll so hopefully this won't take too long

**Comment by christianhelle** [comment]
I hit a few road bumps regarding return types and parameters. I figured out the return types and hopefully will figure out the parameters soon

Current status on generating code against the Swagger Petstore example is this:

```cs
using Refit;
using System.Threading.Tasks;
using System.Collections.Generic;

public interface ISwaggerPetstoreOpenAPI30
{
    [Put("/pet")]
    Task<Pet> UpdatePet();

    [Post("/pet")]
    Task<Pet> AddPet();

    [Get("/pet/findByStatus")]
    Task<ICollection<Pet>> FindPetsByStatus();

    [Get("/pet/findByTags")]
    Task<ICollection<Pet>> FindPetsByTags();

    [Get("/pet/{petId}")]
    Task<Pet> GetPetById(string petId);

    [Post("/pet/{petId}")]
    Task UpdatePetWithForm(string petId);

    [Delete("/pet/{petId}")]
    Task DeletePet(string petId);

    [Post("/pet/{petId}/uploadImage")]
    Task<ApiResponse> UploadFile(string petId);

    [Get("/store/inventory")]
    Task<IDictionary<string, int>> GetInventory();

    [Post("/store/order")]
    Task<Order> PlaceOrder();

    [Get("/store/order/{orderId}")]
    Task<Order> GetOrderById(string orderId);

    [Delete("/store/order/{orderId}")]
    Task DeleteOrder(string orderId);

    [Post("/user")]
    Task CreateUser();

    [Post("/user/createWithList")]
    Task<User> CreateUsersWithListInput();

    [Get("/user/login")]
    Task<string> LoginUser();

    [Get("/user/logout")]
    Task LogoutUser();

    [Get("/user/{username}")]
    Task<User> GetUserByName(string username);

    [Put("/user/{username}")]
    Task UpdateUser(string username);

    [Delete("/user/{username}")]
    Task DeleteUser(string username);
}
```

**Comment by christianhelle** [comment]
@Nonobis I got much further with this and will soon merge this feature into the main branch, where I publish builds to the [OpenVSIX gallery](https://www.vsixgallery.com/extension/d9d55f37-214a-4592-8067-2f9d9906bcfd)

![image](https://user-images.githubusercontent.com/710400/221420924-5ab61a63-1d34-4c9e-87fd-fbd1cbbf523f.png)

I created a new repo dedicated to Refit client interface code generation called [Refitter] (https://github.com/christianhelle/refitter) to speed up development. The [REST API Client Code Generator](https://github.com/christianhelle/apiclientcodegen) repo is getting a bit large and build times are getting longer and longer so it was a bit tiresome to do it here. I also thought that if other IDE integrators find it interesting then they could also pick up the tool themselves

**Comment by Nonobis** [comment]
@christianhelle : Verry nice, thanks you for your work. I hope to test it soon !

**Comment by christianhelle** [comment]
I'll keep this open so we can continue discussions here

**Comment by christianhelle** [comment]
I published version 1.7.0 which includes Refit code generation to the Marketplace. I have only tested this with a small handful of OpenAPI spec files. I would love to hear whether it works for you @Nonobis

**Comment by Nonobis** [comment]
@christianhelle : i wil install the update and test it today against an api. will tell you the result. Thank again !

**Comment by Nonobis** [comment]
I got 2 errors :

- CS1547	Le mot clé 'void' ne peut pas être utilisé dans ce contexte
- CS0306	Le type 'void' ne peut pas être utilisé comme argument de type

Generated code

[Post("/api/v1/Operator/logout")]
Task<void> Logout([Body]LogoutRequest body);

**Comment by christianhelle** [comment]
> I got 2 errors :
> 
> * CS1547	Le mot clé 'void' ne peut pas être utilisé dans ce contexte
> * CS0306	Le type 'void' ne peut pas être utilisé comme argument de type
> 
> Generated code
> 
> [Post("/api/v1/Operator/logout")] Task Logout([Body]LogoutRequest body);

Thanks for trying it out. Do you mind sharing the OpenAPI spec file?

**Comment by Nonobis** [comment]
i will send it on your email after editing a few private value, it's an api currently developped for a client based on an old database ...

**Comment by christianhelle** [comment]
I found the error and implemented the fix. I tested the generated code and verified that it builds in the following target frameworks:

- .NET 7.0
- .NET 6.0
- .NET Standard 2.0
- .NET Standard 2.1
- .NET Framework 4.8 
- .NET Framework 4.8.1
- .NET Framework 4.7.2
- .NET Framework 4.6.2

A new release should up in the marketplace in an hours time

**Comment by Nonobis** [comment]
Compiling with no error here :)

**Comment by christianhelle** [comment]
In case you haven't noticed, v1.7.1 is now out in the Visual Studio Marketplace

**Comment by christianhelle** [comment]
I would be very grateful for a rating or review on the [Visual Studio Marketplace](https://bit.ly/rapicgen-vs2022)

**Comment by Nonobis** [comment]
@christianhelle : Done
