### ISSUE TITLE
Sometimes a NullReference occurs when loading Visual Studio

### ISSUE THREAD

**Issue by kipusoep** [christianhelle/apiclientcodegen#468]
Hi there,

Sometimes when I start Visual Studio with a solution, I get an error popped up:
```
The 'VsPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension.
You can get more information by examining the file 'C:\Users\<user>\AppData\Roaming\Microsoft\VisualStudio\17.0_856bed14\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.
```

Inside this activity log I found the following exception:
```SetSite failed for package [VsPackage]
Source: 'Rapicgen.Core'
Description: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
at Rapicgen.Core.Logging.AppInsightsRemoteLogger.AddTelemetryInitializer(ITelemetryInitializer initializer) in D:\a\apiclientcodegen\apiclientcodegen\src\Core\ApiClientCodeGen.Core\Logging\AppInsightsRemoteLogger.cs:line 33
at Rapicgen.VsPackage.<InitializeAsync>d__6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)```

**Comment by christianhelle** [comment]
Thanks for reporting this! I'll fix this immediately

**Comment by kipusoep** [comment]
v1.6.79, I noticed the newer version just now 😏

**Comment by christianhelle** [comment]
When I looked at the code just now I actually can see an edge case where you start Visual Studio with a debugger attached to the Visual Studio instance itself then you could actually get a NullReferenceException on my extension

I at some point implemented some changes that disabled telemetry when a debugger is attached so I don't collect telemetry while I'm developing the tool

**Comment by christianhelle** [comment]
> v1.6.79, I noticed the newer version just now 😏

Did the update help?

**Comment by Sylv1F** [comment]
I just update 1.6.89 => 1.6.91, it's ok for me, @christianhelle thanks ;-)

**Comment by kipusoep** [comment]
@christianhelle I don't know yet, will find out next week I guess :-)

**Comment by christianhelle** [comment]
A fellow extension author I know recently remarked that considering the size of my user base, my extensions have a surprisingly low amount of ratings/reviews on extensions for VS 2019, and no ratings/reviews at all for my VS 2022 extensions.

I hate to ask, and you of course don't have to, but I would be very grateful for a rating/review on the [Visual Studio Marketplace](https://bit.ly/rapicgen-vs2022)

**Comment by kipusoep** [comment]
@christianhelle thank you sir, you have a great weekend as well! I will leave a review and ask fellow colleagues to do the same.

**Comment by Sylv1F** [comment]
> I just update 1.6.89 => 1.6.91, it's ok for me, @christianhelle thanks ;-)

Fail this morning 

  <entry>
    <record>2409</record>
    <time>2023/01/30 07:35:27.017</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;Rapicgen.Core&apos; Description: La r&#x00E9;f&#x00E9;rence d&apos;objet n&apos;est pas d&#x00E9;finie &#x00E0; une instance d&apos;un objet.&#x000D;&#x000A;System.NullReferenceException: La r&#x00E9;f&#x00E9;rence d&apos;objet n&apos;est pas d&#x00E9;finie &#x00E0; une instance d&apos;un objet.&#x000D;&#x000A;   &#x00E0; Rapicgen.Core.Logging.AppInsightsRemoteLogger.AddTelemetryInitializer(ITelemetryInitializer initializer)&#x000D;&#x000A;   &#x00E0; Rapicgen.VsPackage.&lt;InitializeAsync&gt;d__10.MoveNext()&#x000D;&#x000A;--- Fin de la trace de la pile &#x00E0; partir de l&apos;emplacement pr&#x00E9;c&#x00E9;dent au niveau duquel l&apos;exception a &#x00E9;t&#x00E9; lev&#x00E9;e ---&#x000D;&#x000A;   &#x00E0; System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   &#x00E0; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- Fin de la trace de la pile &#x00E0; partir de l&apos;emplacement pr&#x00E9;c&#x00E9;dent au niveau duquel l&apos;exception a &#x00E9;t&#x00E9; lev&#x00E9;e ---&#x000D;&#x000A;   &#x00E0; System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   &#x00E0; Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{47AFE4E1-5A52-4FE1-8CA7-EDB8310BDA4A}</guid>
    <hr>0x80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by christianhelle** [comment]
Damn! Let me investigate deeper, it seems to work just fine on the machines I test with. I'll set up a couple fresh VM's and see if I can reproduce this

Thanks @Sylv1F

**Comment by christianhelle** [comment]
To avoid blocking you @Sylv1F I will release a hotfix that wraps that sinner method with a catch-all and swallow that error until I can figure what's really wrong.

**Comment by christianhelle** [comment]
@Sylv1F v1.6.92 is now out. Hopefully this resolves your issue

**Comment by Sylv1F** [comment]
> @Sylv1F v1.6.92 is now out. Hopefully this resolves your issue

@christianhelle 1.6.92 is ok and i specify that my current project does not use the extension and it is a project in Xamarin.forms

**Comment by christianhelle** [comment]
@kipusoep are things working from your side as well? I will close this issue now. Please reach out if there is anything wrong in the latest version
