### ISSUE TITLE
Windows ARM64 not supported

### ISSUE THREAD

**Issue by markti** [christianhelle/apiclientcodegen#498]
**Describe the bug**
Windows 11 running in a VM on Mac M1 hardware uses ARM64 architecture.

**Support Key**: `[my-support-key]` *Found in **Tools -> Options -> REST API Client Code Generator - Analytics***

**To Reproduce**
1. Download extension
2. Install extension
3. See error

3/12/2023 10:50:23 AM - Microsoft VSIX Installer
3/12/2023 10:50:23 AM - -------------------------------------------
3/12/2023 10:50:23 AM - vsixinstaller.exe version:
3/12/2023 10:50:23 AM - 17.4.2118-17-4P4Inse-ge4c88902
3/12/2023 10:50:23 AM - -------------------------------------------
3/12/2023 10:50:23 AM - Command line parameters:
3/12/2023 10:50:23 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\markti\Downloads\ApiClientCodeGenerator-VS2022-1.7.3.vsix
3/12/2023 10:50:23 AM - -------------------------------------------
3/12/2023 10:50:23 AM - Microsoft VSIX Installer
3/12/2023 10:50:23 AM - -------------------------------------------
3/12/2023 10:50:24 AM - Initializing Install...
3/12/2023 10:50:25 AM - Extension Details...
3/12/2023 10:50:25 AM - 	Identifier         : d9d55f37-214a-4592-8067-2f9d9906bcfd
3/12/2023 10:50:25 AM - 	Name               : REST API Client Code Generator for VS 2022
3/12/2023 10:50:25 AM - 	Author             : Christian Resma Helle
3/12/2023 10:50:25 AM - 	Version            : 1.7.3
3/12/2023 10:50:25 AM - 	Description        : A collection of Visual Studio custom tools for generating a strongly typed REST API Client from an Open API / Swagger specification file
3/12/2023 10:50:25 AM - 	Locale             : en-US
3/12/2023 10:50:25 AM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator2022
3/12/2023 10:50:25 AM - 	InstalledByMSI     : False
3/12/2023 10:50:25 AM - 	SupportedFrameworkVersionRange : [4.7.2]
3/12/2023 10:50:25 AM - 
3/12/2023 10:50:25 AM - 	SignatureState     : Unsigned
3/12/2023 10:50:25 AM - 	Supported Products : 
3/12/2023 10:50:25 AM - 		Microsoft.VisualStudio.Community
3/12/2023 10:50:25 AM - 			Version : [17.0,18.0)
3/12/2023 10:50:25 AM - 			ProductArchitecture : amd64
3/12/2023 10:50:25 AM - 
3/12/2023 10:50:25 AM - 	References         : 
3/12/2023 10:50:25 AM - 	Prerequisites      : 
3/12/2023 10:50:25 AM - 		-------------------------------------------------------
3/12/2023 10:50:25 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/12/2023 10:50:25 AM - 		Name         : Visual Studio core editor
3/12/2023 10:50:25 AM - 		Version      : [17.0,18.0)
3/12/2023 10:50:25 AM - 
3/12/2023 10:50:25 AM - Signature Details...
3/12/2023 10:50:25 AM - 	Extension is not signed.
3/12/2023 10:50:25 AM - 
3/12/2023 10:50:25 AM - Searching for applicable products...
3/12/2023 10:50:25 AM - Found installed product - Global Location
3/12/2023 10:50:25 AM - Found installed product - Visual Studio Enterprise 2022
3/12/2023 10:50:25 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Expected behavior**
Extension should install on Windows running ARM.

**Screenshots**

![image](https://user-images.githubusercontent.com/3155241/224552634-5395e483-ba23-4a4c-b411-cacb708ec838.png)

**Visual Studio Extension (please complete the following information):**
 - Windows 11 Enterprise
 - Visual Studio Version: Visual Studio Enterprise 2022 (ARM 64-bit) Version 17.4.0
 - Extension Version [e.g. 1.2.6222]

**Comment by christianhelle** [comment]
Thanks for reporting this @markti 

I don't have any ARM64 hardware at hand but I'll see what I can do...

**Comment by christianhelle** [comment]
I can see that's there a simple option to add ARM64 support in the VSIX manifest file so I tried that out in the build attached to this comment

Would you mind trying out this build? -> [ApiClientCodeGenerator-VS2022-1.7.2544.vsix.zip](https://github.com/christianhelle/apiclientcodegen/files/10952473/ApiClientCodeGenerator-VS2022-1.7.2544.vsix.zip)

Since I have no way to really test this, I'm gonna need a bit of help from you @markti to verify

thanks in advance

**Comment by christianhelle** [comment]
I haven't heard from @markti for a while but I have enabled ARM64 support on the Visual Studio extension in [this release](https://github.com/christianhelle/apiclientcodegen/releases/tag/1.7.7) which is available on the Visual Studio Marketplace
