### ISSUE TITLE
Client name setting

### ISSUE THREAD

**Issue by maxkisung** [christianhelle/apiclientcodegen#59]
it would be nice if the client name could be generated from the same name as the swagger file instead of from the swagger doc title.  

for instance, i would name the swagger file FooClient and it would generate a FooClient.cs which would be same name as the class.

**Comment by christianhelle** [comment]
First of all, thanks for the input!

I would prefer to keep the swagger doc title but I could introduce a option called "Use OpenAPI Document Title" with a default value of TRUE, and when set to false will use the swagger file name, or something like that...

What do you think?

**Comment by maxkisung** [comment]
Perfect!!

**Comment by christianhelle** [comment]
Cool! I'll try to build this over the weekend

**Comment by unchase** [comment]
@maxkisung you can use [Unchase OpenAPI (Swagger) Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseopenapiconnectedservice) with more customization.

![Adding Unchase OpenAPI (Swagger) Connected Service in Visual Studio](https://raw.githubusercontent.com/unchase/Unchase.OpenAPI.Connectedservice/master/img/Unchase-OpenAPI-Swagger-Connected-Service.gif)
#### **Read [How-To on medium.com](https://medium.com/@unchase/how-to-generate-c-or-typescript-client-code-for-openapi-swagger-specification-d882d59e3b77)**

**Comment by christianhelle** [comment]
@maxkisung I started implementing this and created issue #61 for specifying an options page for AutoRest

**Comment by christianhelle** [comment]
Hi @maxkisung 

I'm sorry for all the delays. I haven't been working in Windows since the first of October due to a gig change but I finally got myself a proper Windows machine again and I'll finish this up soon. I already implemented the feature a few weeks ago but I haven't been able to test it thoroughly yet

I'll close this issue as soon as I publish the update to the marketplace

**Comment by christianhelle** [comment]
This is now published the the marketplace as version 1.1.708
