### ISSUE TITLE
Getting garbled/binary content when attempting to download JSON definition file (publicly available URL)

### ISSUE THREAD

**Issue by mamift** [christianhelle/apiclientcodegen#620]
**Describe the bug**
Attempting to download https://developers.intellihr.io/docs/v1/swagger.json results in garbled/binary JSON file being saved.
The file is publicly accessible and does not require auth, so it should be reproducible.

**Support Key**: `f9a7fcf` 

**To Reproduce**
1. Add any REST API client (it doesn't matter which one - I've tried them all), and it downloads the above JSON file as binary for some reason (see 2nd screenshot).

**Expected behavior**
The JSON is supposed to download as plain text, not binary.

**Screenshots**
![image](https://github.com/christianhelle/apiclientcodegen/assets/2508444/03c6eff1-fb57-46c6-a88d-95c7d287af77)
![image](https://github.com/christianhelle/apiclientcodegen/assets/2508444/4c8aa2e8-8903-4d66-958b-ff0941c45e3f)

**Visual Studio Extension (please complete the following information):**
 - Visual Studio Version: 2022 17.4.10
 - Extension Version: 1.8.2

**Additional context**
I've tried downloading the JSON file using Powershell and confirmed it does download normally using the command:
`iwr -Uri https://developers.intellihr.io/docs/v1/swagger.json -OutFile ihr.json`

**Comment by christianhelle** [comment]
Thanks for reporting this @mamift 

I'll see what I can do

**Comment by christianhelle** [comment]
@mamift As a temporary work-around you can replace the contents of the already downloaded `Swagger.json` file with the expected content and the Visual Studio custom tool interface should kick in immediately upon saving changes to the `Swagger.json` file

**Comment by christianhelle** [comment]
@mamift  I found out what's wrong... The URI to the OpenAPI spec you're using uses gzip content encoding and apparently this needs to be handled manually. I know what to do and I'll release a fix today

**Comment by christianhelle** [comment]
By the way @mamift, the OpenAPI spec you shared in this issue seems to be full of errors (573) and warnings (161) when I tried opened it in Stoplight Studio. I don't think any of the C# code generators I know can generate code from it

**Comment by christianhelle** [comment]
The fix for this issue is now released to the Marketplace as [v1.8.3](https://github.com/christianhelle/apiclientcodegen/releases/tag/1.8.3)

**Comment by christianhelle** [comment]
@mamift I hope it's not too much to ask but I would be very grateful for a rating or review on the [Visual Studio Marketplace](https://bit.ly/rapicgen-vs2022)
