### ISSUE TITLE
Bad kiota installation detection

### ISSUE THREAD

**Issue by Hiller** [christianhelle/apiclientcodegen#775]
According to https://github.com/christianhelle/apiclientcodegen/blob/master/src/Core/ApiClientCodeGen.Core/Installer/DependencyInstaller.cs
you are always starting kiota installation and detect whether it's installed by presence in error output SINGLE QUOTED tool ID
('microsoft.openapi.kiota') while dotnet is outputing it DOUBLE QUOTED.  (Most probably it's a  dotnet localization issue)
I guess the best way to detect whether kiota is installed by checking its version running 
kiota --version 
if kiota is installed it will succeed and return version
if case of failure you can initiate installation.

**Comment by christianhelle** [comment]
@Hiller Thanks for taking the time to report this

That's a good idea to just check the version, thanks for suggesting it. I will try it out
