### ISSUE TITLE
Half of the provided client generators don't work but show an error

### ISSUE THREAD

**Issue by johannes-ziegltrum** [christianhelle/apiclientcodegen#836]
**Describe the bug**
Half of the provided client generators don't work but show an error.

**Support Key**: `333dc89` *Found in **Tools -> Options -> REST API Client Code Generator - Analytics***

**To Reproduce**
1. Create a 'ASP.NET Core Empty' Project with '.NET 8.0 (Long Term Support)' framework
2. Add a OpenAPI yaml or json file to the project
3. Right click on the file -> REST API Client Generator -> Generate with NSwag (v14.0.3) -> success
4. Right click on the file -> REST API Client Generator -> Generate with OpenAPI Generator (v7.4.0) -> error (see sreenshot)
5. Right click on the file -> REST API Client Generator -> Generate with Microsoft Kiota (v.1.12.0) -> error (see sreenshot)
6. Right click on the file -> REST API Client Generator -> Generate with Swagger (3.0.34 - Outdated) -> error (see sreenshot)
7. Right click on the file -> REST API Client Generator -> Generate with AutoRest (v3.0.0-beta - Outdated) -> success
8. Right click on the file -> REST API Client Generator -> Generate with Rifitter (v0.9.9) -> success

**Expected behavior**
All client generators should work.

**Screenshots**
![Generate with OpenAPI Generator (v7 4 0)](https://github.com/christianhelle/apiclientcodegen/assets/5843004/9904bd66-fca8-4fcc-ad86-9eed9e5d6b6e)
![Generate with Microsoft Kiota (v 1 12 0)](https://github.com/christianhelle/apiclientcodegen/assets/5843004/dd7452a4-58db-4692-8327-2b104e154089)
![Generate with Swagger (3 0 34 - Outdated)](https://github.com/christianhelle/apiclientcodegen/assets/5843004/cfb5c48f-16c8-4e9f-a706-35558637e7e4)

**Visual Studio Extension (please complete the following information):**
 - Visual Studio Version: Microsoft Visual Studio Community 2022 (64-bit) Version 17.9.5
 - Extension Version: REST API Client Code Generator for VS 2022 Version 1.9.8

**Comment by christianhelle** [comment]
@johannes-ziegltrum thanks for taking the time to report this

From the provided support key, I can see from the error logs that the extension fails to find the java.exe from the Java runtime (or SDK). **OpenAPI Generator** and **Swagger Codegen CLI** depends on the Java runtime

As for Kiota, I can't see what's wrong really but it fails to read the path parameters that the extension passes to the CLI tool. Basically my extension will install the latest version of Kiota and launch it using the following command

```pwsh
kiota generate -l CSharp -d [absolute path to]\OpenApiExample.yaml -o [temp path] -n [namespace]
```

I can see from the error logs that Kiota complains about the path to the YAML file. I'll need to investigate a bit more to know why this is exactly. This could be a bug in Kiota itself but I'll see what I can do to confirm first. I have unfortunately only tested my extension on machines running English.

I'll investigate in detail after the holidays

Have a nice easter

**Comment by christianhelle** [comment]
@johannes-ziegltrum If you know that you have Java installed and the extension can't find it then you can specify the path to java.exe from the extension options, **Tools -> REST API Client Code Generator -> General -> Path to java.exe**

![image](https://github.com/christianhelle/apiclientcodegen/assets/710400/181f9cda-85e9-498a-95bb-cf63ad86b43c)

**Comment by christianhelle** [comment]
I'll keep this open and associate the fix regarding showing an informative error message when the tool can't find java.exe
