### ISSUE TITLE
Rifitter => Refitter typo

### ISSUE THREAD

**Issue by dammitjanet** [christianhelle/apiclientcodegen#844]
**Describe the bug**
There is a typo in one of the menus

**Support Key**: `[ecbee24`

**To Reproduce**
1) Right click an existing OpenAPI json file
2) Expand the REST API Client Generator
3) The Refitter entry in the shown menu has a typo

**Expected behavior**
The menu to read Refitter

**Screenshots**
![Screenshot 2024-04-10 at 09 17 11](https://github.com/christianhelle/apiclientcodegen/assets/952723/212d660e-6ac4-43a0-94d4-c38435a0b758)

**Visual Studio Extension (please complete the following information):**
 - Visual Studio Version: 2022 Community
 - Extension Version 1.9.8

**Additional context**

**Comment by christianhelle** [comment]
Thanks for taking the time to report this @christianhelle

**Comment by christianhelle** [comment]
That's an embarrassing issue! I haven't touched that code in years 😭
