### ISSUE TITLE
Refitter file gets overwritten

### ISSUE THREAD

**Issue by dammitjanet** [christianhelle/apiclientcodegen#907]
**Describe the bug**
After using #879 to import and create a refitter file, updating the the source api json file, overwrites the refitter file

**Support Key**: `ecbee24`

**To Reproduce**
1. Create a new refitter with the VS tool so that it generates the OpenAPI json file, the refitter file, and the underlying .cs file
2. Modify the refitter file and save
3. Modify the text of the OpenAPI json file, this automatically regenerates the refitter file
4. The changes made in 2 have been lost

**Expected behavior**
If a refitter file already exists within the project, then the file should not be overwritten as any changes made are lost. 

**Screenshots**
n/a

**Visual Studio Extension (please complete the following information):**
 - Visual Studio Version: 2022
 - Extension Version 1.10.1

**Additional context**
n/a

**Comment by christianhelle** [comment]
@dammitjanet thanks for pointing this out and taking the report this. I guess it went a bit too quick with implementing this feature
