### ISSUE TITLE
BasePath in default constructor will cause exception

### ISSUE THREAD

**Issue by Mahdi-Farhani** [christianhelle/apiclientcodegen#92]
Hi,
When I want to create a new configuration I got an Invalid Url exception. I checked the code and I found static constructor will cause this exception. 
GlobalConfiguration derived from Configuration and it will be calling the default constructor of Configuration so the BasePath will be set with the default value which is "/". Thus, the RestClient will try to instanced by "/" for basePath and it will throw an exception.

Am I done something wrong to initialize an ApiClient? 

```
var configuration = new ApiClient.Client.Configuration()
                {
                    BasePath = BaseUrl,
                    AccessToken = token
                };

                var server = new ApiClient.Api.MembershipApi(configuration);
```
And another thing is the other constructor will call the default constructor too and again it will throw an invalid Url exception.
   ```
public Configuration(
            IDictionary<string, string> defaultHeader,
            IDictionary<string, string> apiKey,
            IDictionary<string, string> apiKeyPrefix,
            string basePath = "/") : this()
```

I think this constructor shouldn't call the default constructor.

**Comment by Mahdi-Farhani** [comment]
And another thing is the other constructor will call the default constructor too and again it will throw an invalid Url exception.
   ```
public Configuration(
            IDictionary<string, string> defaultHeader,
            IDictionary<string, string> apiKey,
            IDictionary<string, string> apiKeyPrefix,
            string basePath = "/") : this()
```

I think this constructor should call default constructor.

**Comment by christianhelle** [comment]
Which code generator are you using for this?

**Comment by Mahdi-Farhani** [comment]
> Which code generator are you using for this?

Swagger

**Comment by christianhelle** [comment]
Let me play around a bit with the Swagger generated code. I haven't really tried using Swagger Codegen CLI or OpenAPI Generator in production systems. 

I strongly recommend trying out NSwag as the generator. The generated code will basically just accept an instance of HttpClient for all HTTP calls which you can preconfigure. It also has the least dependencies

**Comment by christianhelle** [comment]
I was playing a bit with this yesterday and I generated code using the Swagger Codegen CLI generator and used the [Swagger Petstore OpenAPI spec file](https://petstore.swagger.io/v2/swagger.json)

I used RequestBin to test how the HTTP request looks like without building an actual API

This following code works fine where I use an instance of the generated `Configuration` class

```
new PetApi(
    new Configuration()
    {
        BasePath = "https://381ec7c2a00e3e43067dd35f9cffb326.m.pipedream.net",
        AccessToken = "some-oauth2-token"
    })
    .AddPet(new Pet(name: "", photoUrls: new List<string>()));
```

I also tried the approach that uses the static `Configuration.Default` instance and the code also works fine

```
Configuration.Default.BasePath = "https://381ec7c2a00e3e43067dd35f9cffb326.m.pipedream.net";
Configuration.Default.AccessToken = "some-oauth2-token";
new PetApi().AddPet(new Pet(name: "", photoUrls: new List<string>()));
```

Both ways resulted in the same event in RequestBin

```
{
  "method": "POST",
  "path": "/pet",
  "query": {},
  "headers": {
    "x-forwarded-for": "217.63.114.54",
    "x-forwarded-proto": "https",
    "x-forwarded-port": "443",
    "host": "381ec7c2a00e3e43067dd35f9cffb326.m.pipedream.net",
    "x-amzn-trace-id": "Root=1-5f51f2f1-60fecb40dcf324702af8d3ec",
    "content-length": "26",
    "authorization": "Bearer some-oauth2-token",
    "accept": "application/json, application/xml, text/json, text/x-json, text/javascript, text/xml",
    "user-agent": "Swagger-Codegen/1.0.0/csharp",
    "accept-encoding": "gzip, deflate",
    "content-type": "application/json"
  },
  "bodyRaw": "{\"name\":\"\",\"photoUrls\":[]}",
  "body": {
    "name": "",
    "photoUrls": []
  }
}
```

Personally, I'm not a fan of the code that Swagger Codegen CLI or OpenAPI Generator creates. AutoRest does a better job, but is still inferior to NSwag

I can't really do anything about the actual generated code since I just piggy back on the code generators I support
