### ISSUE TITLE
New version of the Restsharp changed the signature of Addfile parameter

### ISSUE THREAD

**Issue by Mahdi-Farhani** [christianhelle/apiclientcodegen#93]
Hi,
When I got the new version of Restsharp (106.11.4), I realized the PrepareRequest method in ApiClient should be changed due to the AddFile signature in Restsharp is changed
It would be nice to consider in your next version.

**Comment by christianhelle** [comment]
Yes, I'm aware of this and I'm pretty sure that Swagger is aware of this too. This has been the case for a few months now and since I only piggy back on top of Swagger Codegen CLI, OpenAPI Generator, AutoREST, and NSwag, I have little to no control over how the code is generated, except for the options they expose in their toolset

**Comment by christianhelle** [comment]
I'll keep this issue open until a version of the Swagger Codegen CLI and OpenAPI Generator fixes this issue

**Comment by chrbkr** [comment]
According to [this issue](https://github.com/OpenAPITools/openapi-generator/issues/7498), OpenAPI updated RestSharp a while ago, but only for csharp-netcore, not for csharp. Apparently, despite the name it's .NET standard, not (just) .NET Core.

**Comment by christianhelle** [comment]
I use these arguments for OpenAPI Generator

```
var arguments =
    $"-jar \"{jarFile}\" generate " +
    "-g csharp " +
    $"--input-spec \"{swaggerFile}\" " +
    $"--output \"{output}\" " +
    "-DapiTests=false -DmodelTests=false " +
    $"-DpackageName={defaultNamespace} " +
    "--skip-overwrite ";
```

I'll start effort getting everything to work using `csharp-netcore`

Thanks for pointing this out @chrbkr

**Comment by christianhelle** [comment]
I have a branch that now generates code using the latest versions of NuGet packages when generating code using OpenAPI Generator

**Comment by christianhelle** [comment]
This is now fixed when generating code using OpenAPI Generator. Let me see what I can do regarding Swagger Codegen CLI

**Comment by christianhelle** [comment]
I unfortunately don't see Swagger Codegen CLI fixing this any time soon so I will just close this issue
