### ISSUE TITLE
Kiota sdk gen output 

### ISSUE THREAD

**Issue by pyro5ive** [christianhelle/apiclientcodegen#956]
When using the Koita code gen from command prompt, the output libraries are organized into folders/directories/namespaces/files. 

When using the tool in VS 2022 Community, the output libraries are crammed into one .cs file.   

I would like the tool to not merge everything into one .cs file.

**Comment by christianhelle** [comment]
@pyro5ive There is an option for that under the extensions settings page

![image](https://github.com/user-attachments/assets/5d3d51cf-d138-4568-bb1d-d3aa9f6ba76b)

The output will look something like this

![image](https://github.com/user-attachments/assets/435f1854-1d47-48b7-9648-bfb5442fb487)

There is also an option to generate code by right-clicking on the Kiota settings file, in case you do customization to the kiota generator options

**Comment by christianhelle** [comment]
I'm closing this issue since the feature requested is already implemented
