### ISSUE TITLE
OpenAPI - default Target Framework NET8.0 missing

### ISSUE THREAD

**Issue by patrvlie** [christianhelle/apiclientcodegen#960]
Hello Christian,

Thank you for your effort on this incredible extension.

I am using VS2022.

I have noticed the default "targetFramework" option for OpenAPI Generator is supposed to be :  net8.0
It is mentioned in their online documentation for version 7.7.0:
https://openapi-generator.tech/docs/generators/csharp/

Yet in the list of available Target Framework under the extension configuration panel, I do not see listed "net8.0", it stops at "Net60".

I would guess this was not intended.
Could you please confirm ?

Thank you
Regards
Patrick

![vs2022-options-OpenAPI](https://github.com/user-attachments/assets/1fbb4552-ce85-4b86-ac84-98485425ab04)

**Comment by christianhelle** [comment]
> Hello Christian,
> 
> Thank you for your effort on this incredible extension.

Thank you for the kind words @patrvlie 

> I have noticed the default "targetFramework" option for OpenAPI Generator is supposed to be : net8.0 It is mentioned in their online documentation for version 7.7.0: https://openapi-generator.tech/docs/generators/csharp/
> 
> Yet in the list of available Target Framework under the extension configuration panel, I do not see listed "net8.0", it stops at "Net60".
> 
> I would guess this was not intended. Could you please confirm ?

This is not intended, and I must have forgotten to keep the option updated. It's a straightforward fix, we need to add `Net80` to the [`OpenApiSupportedTargetFramework`](https://github.com/christianhelle/apiclientcodegen/blob/master/src/Core/ApiClientCodeGen.Core/Options/OpenApiGenerator/OpenApiSupportedTargetFramework.cs) enum and all the extension will deal with the rest. 

Thanks for taking the time to report this. I'll address this immediately
